language: node_js
node_js:
  - '10'
install:
  - npm i
script: npm test && npm run lint && npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        all_branches: true